### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by pfefferle** [comment]
@dshanske can your re-review?

**Comment by dshanske** [comment]
I checked, we were at 5.3 before this PR

**Comment by pfefferle** [comment]
OK, understood. I will fix this for the actual requirements and then we can raise them as required by the upcoming changes.

**Comment by dshanske** [comment]
Maybe someday, I will do something with mf2 testing under site health, which would require the mf2 library

**Pull request merged**
