### PR TITLE
Mostly Icon Fixes

### PR DESCRIPTION
**Pull request by dshanske**

### CODE REVIEW

**Comment by pfefferle** [comment]
1. Please do not mix too many different changes in one merge request!

2. Why have you changed the license?

**Review by pfefferle — CHANGES_REQUESTED** [review]
Please remove the CC0 license file.

**Comment by dshanske** [comment]
I didn't relicense, I included the license file for the icons in a subdirectory.

**Comment by dshanske** [comment]
The changes were all to support the icon change. I switched to the same icon generation system that I adopted in Syndication Links. Scripted generation of the CSS. No more hard coded icon mappings, etc.

**Review by pfefferle — APPROVED** [review]

**Comment by pfefferle** [comment]
you are right, sorry for the confusion!

**Pull request merged**
