### PR TITLE
Add default value to single author and author id

### PR DESCRIPTION
**Pull request by asuh**
Fixes issue where <link rel="me"> is missing from head upon plugin activation

### CODE REVIEW

**Comment by dshanske** [comment]
This would be incorrect as of WordPress 4.7. The default is set now in register_setting, not get_option.

**Comment by asuh** [comment]
If you look at my 2nd commit, adding the `register_settings` functions was the next solution I could find to make the `<link rel="me"...>` element to show up in the header.

I know what I committed won't be used but this at least demonstrates that `iw_single_author` and `iw_default_author` aren't inheriting any value in the latest version of this file without the above functions being set.

**Comment by dshanske** [comment]
The question is what differs from the test setup I used to yours. I am going to try a few things.

**Comment by asuh** [comment]
For what it's worth, I created new WP installation with nothing in it but the plugin activated and twitter in my bio options. Same problem as other site.

http://www.micahcambre.com/indie

**Comment by dshanske** [comment]
I think I have an idea as to the issue. Where the registration is performed. It looks like it should be loaded earlier. Let me try that.

**Pull request closed without merging**
