### PR TITLE
H-Card Widget and Related Inclusions

### PR DESCRIPTION
**Pull request by dshanske**

### CODE REVIEW

**Review by miklb — APPROVED** [review]

**Comment by Arcanewinds** [comment]
Hey, this update has introduced an error into friend's website, thought you'd like to know:

Fatal error: Can't use method return value in write context in plugins/indieweb/includes/class-hcard-user.php on line 495

Triggered by visiting the website root.
Apologies that I'm unable to provide more information.

**Comment by christianwach** [comment]
> Apologies that I'm unable to provide more information.

Your friend's server is running a version of PHP less than 5.5. 
For a quick fix, change `! empty( $user->get( 'tel' ) )` to `$user->get( 'tel' )` on line 495.

**Comment by dshanske** [comment]
The plugin should work on 5.3 and above. We'll address this.

**Comment by Arcanewinds** [comment]
Impressively quick responses, great dedication! I've passed that information on.

Best wishes!

**Pull request merged**
