### PR TITLE
Add relme to REST API

### PR DESCRIPTION
**Pull request by dshanske**
This adds the rel-me links from the profile into the REST API user endpoint. Since the widget also shares these, there is not a privacy issue.

### CODE REVIEW

**Comment by pfefferle** [comment]
Indents 😉

**Comment by dshanske** [comment]
Where?

**Comment by pfefferle** [comment]
The line with the `return`?!?

**Comment by dshanske** [comment]
> The line with the `return`?!?

It's an anonymous function..that isn't aligned right?

**Comment by pfefferle** [comment]
I fixed it.

Why this change?

**Comment by dshanske** [comment]
@pfefferle And I thought I was getting better at that.

**Comment by dshanske** [comment]
@pfefferle I've been contemplating distributed identity verification between WordPress sites. Related to the IndieAuth enhancements.

**Comment by pfefferle** [comment]
So the indieweb plugin is then required to do so?

**Comment by dshanske** [comment]
The Indieweb plugin is already sharing this information in the header or in a widget.

**Comment by pfefferle** [comment]
If you are using it...!

**Comment by dshanske** [comment]
@pfefferle Correct. You have the option that disables that feature set up, so that would disable this as well.

**Comment by pfefferle** [comment]
But you are planning to require this plugin for the delegated authentication feature?

**Comment by dshanske** [comment]
> But you are planning to require this plugin for the delegated authentication feature?

No, I have a rel parser in IndieAuth, will fall back on that if needed.

**Comment by pfefferle** [comment]
The PHP 5.2 check is broken... I think it is because of the anonymous function...

**Comment by dshanske** [comment]
@pfefferle Want to bump minimum to 5.4 or 5.6? Considering WordPress is doing the same?

**Comment by pfefferle** [comment]
5.6 is enough I think!

**Comment by pfefferle** [comment]
Should I do it?

**Comment by dshanske** [comment]
@pfefferle I can. One second.

**Review by pfefferle — APPROVED** [review]
I am curious what you are planning here...

**Comment by dshanske** [comment]
@pfefferle I have another idea for it. Nickname cache. But the IndieAuth one is the one I added it for.

**Pull request merged**
