### PR TITLE
Improvements to Support New Stable Release

### PR DESCRIPTION
**Pull request by dshanske**
Realized last night there was an issue that had been pushed but not updated on wordpress.org, so took some time to knock down some outstanding issues so we can release a new version. Right now, people are getting the 'Not Tested with your Version' warning.

- Replaces TGM Plugin Activation with a simplified plugin installer without the annoying notices and with a nicer visual format.
- Adds a setting to enable/disable the override of the author page UR per request
- Passes through URLs if they  are set as silo properties and removes @ if found in a Twitter handles, eliminating the reported user meta issue
- Internationalizes several missing strings 
- Updates to the new register_setting format
- Removes all Github repo installs in favor of WordPress.org repos only. Would like to add more recommendations. I'd like to see if wordpress-uf2 and indieweb-press-this could be updated and go on the .org repo for that reason. I think new users don't want to worry about development versions.
- Minor Fixes

### CODE REVIEW

**Comment by miklb** [comment]
Tested the new extension page with `4.7.5` installing & activating each plugin with no issues. 

The only thing I'm curious about is on the options page, `Use User URL for Author` seems ambiguous, there is no field for `User URL`, but there is a field for `Website`. May seem trivial but could be confusing to a new user.

**Comment by dshanske** [comment]
It can only be disabled if is_multi_author is true.

**Comment by pfefferle** [comment]
I added a second user and still can't disable it.

**Comment by dshanske** [comment]
Author, not user. The user has to have made a post.

**Comment by pfefferle** [comment]
hmmm... perhaps we should add a hint for that... not that easy to understand...

**Comment by dshanske** [comment]
Agreed. I'll push a text change before I merge.

**Comment by pfefferle** [comment]
cool! thanks! 👍

**Comment by dshanske** [comment]
@pfefferle Would you be able to push to .org?

**Comment by pfefferle** [comment]
perhaps we should hide this in a future release if `is_multi_author` is false, to be more user friendly.

**Comment by pfefferle** [comment]
@dshanske a small hint... have you read about semver? you changed a lot and you dropped a complete lib... you could at least use a minor version... just saying ;)

**Comment by dshanske** [comment]
Not a bad idea. Or disable the checkbox.

**Comment by dshanske** [comment]
I probably should have updated to 3.1.0. I just wasn't thinking.

**Comment by pfefferle** [comment]
Have you already released the new version? if not, we should change the version... will give my +1 asap...

**Comment by dshanske** [comment]
Give me a second there

**Pull request merged**
