### PR TITLE
Update Icons

### PR DESCRIPTION
**Pull request by dshanske**
This updates the icons based on the latest Simple Icons update, which includes a Micro.blog icon, which seems to be popular lately. Also removes a bunch of old files.

### CODE REVIEW

**Comment by pfefferle** [comment]
Can you also address the license „problem“?

**Comment by dshanske** [comment]
Which? I incorporated the license file for Simple Icons.

**Comment by pfefferle** [comment]
Move the license to the correct folder, where the icons are located, or move the icons back to the node_modules folder

**Comment by dshanske** [comment]
The icons are not included, only a consolidated file built from them, but I think putting it in the other directory works.

**Comment by pfefferle** [comment]
If you generate it, I would prefer to move the license!

**Comment by dshanske** [comment]
Completely forgot about this PR. Refreshing it.

**Pull request merged**
