### PR TITLE
Semantic Versioning

### PR DESCRIPTION
**Pull request by dshanske**
Should have been 3.1.0. 

Hope everyone likes the changes. I think the new plugin installer looks much better, and I fixed the biggest issues with the rel-me additions.

### CODE REVIEW

**Comment by pfefferle** [comment]
should I still release the .org version

**Comment by dshanske** [comment]
If you can. We had two people this week having trouble with the plugin. That's what prompted me to do a quick update of a few things.

**Comment by pfefferle** [comment]
sure, will do! thanks for your hard work!

**Comment by dshanske** [comment]
It was my pleasure. More coming. I want to do as much as I can before the IW Summit. I just arranged to go.

**Pull request merged**
